name = "yumegate-backend"
compatibility_date = "2024-08-22"
compatibility_flags = [ "nodejs_compat" ]

[vars]
HASURA_GRAPHQL_ENDPOINT = "https://teaching-slug-86.hasura.app/v1/graphql"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[placement]
mode = "smart"